### ISSUE TITLE
Bug - TConsturct bows dont work when added to bow override section at configs

### ISSUE THREAD

**Issue by alperen-bircak** [Armourers-Workshop/Armourers-Workshop#102]
title

**Comment by RiskyKen** [comment]
When the game is loading do you get any errors in the log like "Invalid bow override in config file" or "Unable to override item renderer for" you may need to turn on showing the log on whatever launcher you are using.

**Comment by Alexismachina** [comment]
No, nothing printed in the log.

**Comment by RageNTonic** [comment]
i uh did have a problem with this where tconstruct wouldnt load. i did end up looking in the log andit said {[Armourer's Workshop]: Unable to override item renderer for: TConstruct - longbow} along with the other items i tried to overide

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
