### ISSUE TITLE
Bug - Render error of equipment cubes with AMD graphic card (green cubes)

### ISSUE THREAD

**Issue by CatMe0w** [Armourers-Workshop/Armourers-Workshop#105]
Basic information of my system and graphic card

> Radeon Software Version - 16.4.1
> Radeon Software Edition - Crimson
> Graphics Chipset - AMD Radeon R7 200 Series (it's R7 260X )
> Memory Size - 1024 MB
> Memory Type - GDDR5
> Core Clock - 1120 MHz
> Windows Version - Windows 10 (64 bit)
> System Memory - 12 GB
> CPU Type - Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz

Some pictures of this issue:

> http://imgur.com/a/xSdpc

Description:
Ugh.. When I was using AMD Catalyst 15.9, this problem was started to appear. Until now, this problem is still existing in Crimson 16.4.1. Please fix it, thanks.

**Comment by RiskyKen** [comment]
I can't really tell from the screen shots but am guessing the blocks are not showing the correct colour?

Can you give me a mod list. Just do a debug crash to get the list (Hold F3 + C for about 10 seconds)

also you make sure you are using the latest version on the mod: http://minecraft.curseforge.com/projects/armourers-workshop/files

I have seen this issue on some YouTube videos but have been unable to reproduce it on my system, I think it's an AMD issue will need to test it on another system. :|

**Comment by CatMe0w** [comment]
Yes, your guess is right.
There is the crash report: http://pastebin.com/wBrM8Nd7

**Comment by RiskyKen** [comment]
Is this only happening on glowing blocks?

**Comment by CatMe0w** [comment]
No. All kinds of equipment cube have this problem. Here is the picture about it.
http://imgur.com/sgiXWy0

**Comment by LordPhrozen** [comment]
Is this still an issue?

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
