### ISSUE TITLE
AW renders armor pieces on the wrong mannequin's body parts if RenderPlayerAPI is installed

### ISSUE THREAD

**Issue by EzerArch** [Armourers-Workshop/Armourers-Workshop#110]
If Smart Moving is installed, AW renders armor pieces on the wrong mannequin's body parts.

Full body armor:
![2016-05-02_00 05 29](https://cloud.githubusercontent.com/assets/6743303/14946517/9d4f1b20-0ff9-11e6-9665-b66716322cf5.png)
![2016-05-01_23 35 24](https://cloud.githubusercontent.com/assets/6743303/14946516/9d4cae44-0ff9-11e6-9901-f669026a72cf.png)

Only pants:
![2016-05-01_22 28 44](https://cloud.githubusercontent.com/assets/6743303/14945967/705f68f2-0ff1-11e6-8145-ce0068b4dbab.png)
![2016-05-01_22 54 49](https://cloud.githubusercontent.com/assets/6743303/14945968/706033f4-0ff1-11e6-9c12-9e145daceac9.png)

I'm using the latest AW version with latest 1.7.10 SM version.

**Comment by RiskyKen** [comment]
Can you try this version and tell me if it works. I think this has maybe been fixed but I never put out the build. http://puu.sh/oDnoK/e946773d65.jar

This is the current dev version please make a copy of your world before installing. Skins created in this version may not updated to the next version. (although they really should)

**Comment by EzerArch** [comment]
> Can you try this version and tell me if it works.

It doesn't.

**Comment by EthanJJC** [comment]
Did you off the "Chest armour render"?

**Comment by TheChronomancer** [comment]
Uh riskyken, the version you put here causes my skin to bug out (meaning it looks all pink and black)

**Comment by RiskyKen** [comment]
@TheChronomancer please make a new issue and post your mod list.

**Comment by RiskyKen** [comment]
Only when Smart Moving is installed that's strange. What armours are you having issues with?

Seems to be working for me :S

http://puu.sh/oIcOt/b324442f16.png

**Comment by EzerArch** [comment]
> What armours are you having issues with?

Vanilla armors: leather, diamond, golden...

It's a very weird bug. Firstly, the mannequins load right:

![2016-08-30_00 50 39](https://cloud.githubusercontent.com/assets/6743303/18075551/2a0bc274-6e4c-11e6-94fa-4cf674fd8e35.png)

Then once I press F5:

![2016-08-30_00 50 51](https://cloud.githubusercontent.com/assets/6743303/18075555/303030fe-6e4c-11e6-9956-7d4b7f9ccf6f.png)

And as you can see here, my (backup) world is a wreck, since I had removed all mods except:
Armourers-Workshop-1.7.10-0.39.6.jar
OptiFine_1.7.10_HD_U_D6.jar
PlayerAPI-1.7.10-1.4.jar
RenderPlayerAPI-1.7.10-1.4.jar
SmartMoving-1.7.10-15.6.jar
SmartRender-1.7.10-2.1.jar
Forge 1614

**Comment by EzerArch** [comment]
Since I managed to solve that issue, I'm posting these leftovers in a separate post.

1. The leather_layer_2_overlay and leather_layer_1 (torso part) do not follow the model rotation: [GIF 1](https://cloud.githubusercontent.com/assets/6743303/18076506/e3e09cd0-6e54-11e6-8970-15b8dd776522.gif)

**Comment by EzerArch** [comment]
I recorded a video showing how each armor piece (chain mail set) rotates: https://youtu.be/y5cq5c2LKC0
(the video was recorded with the mannequin facing south)

Key points:
* Head:
  - Head wear: rotates 2x faster
* Torso:
  - Chest:
    - X axis: rotates 2x faster
    - Y and Z axes: don't rotate.
  - Arms: their pivots at torso pivot.
* Legs:
  - Limbs: their pivots at torso pivot.
* Feet:
  - Limbs: their pivots at torso pivot.

**Comment by LordPhrozen** [comment]
Updated title to reflect actual issue.

**Comment by EzerArch** [comment]
> Updated title to reflect actual issue.

Did you? For me it looks the same.

**Comment by LordPhrozen** [comment]
I did now :D

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
