### ISSUE TITLE
Item spritesheet rendering on player head when getting hurt, if SM is installed

### ISSUE THREAD

**Issue by EzerArch** [Armourers-Workshop/Armourers-Workshop#117]
This one is a bit hard to explain. Just a visual nuisance.

**The correct behavior:** when a player gets hurt, its model renders a "reddish" overlay for a few tics.

![2016-05-20_03 18 17](https://cloud.githubusercontent.com/assets/6743303/15419063/e7bdeb2a-1e39-11e6-8e29-a48cf949daa0.png)

**What is happening:** when a player gets hurt, its model's head renders an item spritesheet wrapped on it. I can spot some vanilla and Galacticraft items on it. The other parts seem okay.

![2016-05-20_02 46 31](https://cloud.githubusercontent.com/assets/6743303/15418957/4fd3e5bc-1e39-11e6-8c0b-0a5c34f99126.png)

I removed Galacticraft and Optifine to reproduce the bug, since these mods affect the rendering. The bug stopped from happening after I removed SmartMoving-1.7.10-15.6.jar.

![aws-sm](https://cloud.githubusercontent.com/assets/6743303/15419167/aa50750e-1e3a-11e6-96ab-a3fb00db0eef.gif)

This bug only happens if:
- I'm using AWS 0.38 or 0.39.
- SmartMoving is installed.
- My character is using a AWS piece.

**Comment by LordPhrozen** [comment]
How do i give you a medal for this level of detail in a bug report....

thank you so much.

**Comment by EzerArch** [comment]
Want more details?

The thing that is being rendered around the player, instead of the hurt overlay, is an image atlas. The game renders a different kind of atlas depending on the item you hold:
- Hold an item: renders the item atlas.
- Hold a block: renders the block atlas.
- Hold a 3D model item/block: render the png used for that model.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
