### ISSUE TITLE
Tinker's Construct Javelins

### ISSUE THREAD

**Issue by RoseDAmour** [Armourers-Workshop/Armourers-Workshop#129]
I am curious if this is a bug or if I messed something up. I noticed you listed Tinkerer's Construct as being compatible with Armourer's Workshop but I can't get the javelin to work. Any ideas?

Here's my config:
    # List of bows that can have skins applied.
    # Format [mod id:item name]
    # 
    #  [default: [minecraft:bow]]
    S:bowOverrides <
        minecraft:bow

```
    TConstruct:longbow
    TConstruct:shortbow
    TConstruct:shuriken
    TConstruct:javelin
    TConstruct:crossbow
    TConstruct:throwingknife
 >
```

**Comment by LordPhrozen** [comment]
try using the command to add it to the config. it may not be named what you think its named. please try this and let us know.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
