### ISSUE TITLE
MPM and Armourer's Workshop Skin Conflicts

### ISSUE THREAD

**Issue by zhubwat** [Armourers-Workshop/Armourers-Workshop#213]
When I have AW 0.47.1 installed alongside MPM 1.7.10b, the skins in Armourer's Workshop don't work.

By that, I mean, I have turned off texturePainting, tried both skinRenderTypes, and a bunch of other config options, but skins don't show up. It seems to be a problem with URL skins, seeing as I want to use URL skins, but them being incompatible with texturePainting turned on, which in turn makes skins not work for me without turning it on... but I can't use a URL skin.
Attachments, like the blocks placed in the Armourer show, and work as normal, but anything painted onto the skin directly doesn't show. Again, turning off texturePainting makes it work.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
