### ISSUE TITLE
Compatibility with "Ships mod" and "Archimedes' Ships mod"

### ISSUE THREAD

**Issue by ghost** [Armourers-Workshop/Armourers-Workshop#224]
Armourer's workshop custom blocks do not render when the ships are activated, and the blocks also cause odd rendering issues to the players around the ship.

**Comment by RiskyKen** [comment]
Can you post a screenshot of the rendering issues?

**Comment by LordPhrozen** [comment]
Oh. This mod turns the whole ship into an entity. this is likely where the issue is, imo. probably has no idea how to handle an AW block skin.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
