### ISSUE TITLE
Body Part Space Extension

### ISSUE THREAD

**Issue by LordPhrozen** [Armourers-Workshop/Armourers-Workshop#232]
Head is enormous, 
Wings are enormous. 

I think the other body parts need some love and expansion. 

-Extend Legs to the floor ( to make longer waist items )
-Extend Feet up by 8 blocks ( to make taller shoes )
-Extend Chest forward by 16 blocks, and backwards by 16 blocks ( to make more uniquely shaped models)
![boundries](https://user-images.githubusercontent.com/7896457/40254686-020af866-5aaa-11e8-8f38-3a42e11c2e88.png)

Blue is Max Head size, Red is max chest/arm/leg

**Comment by SAGESSE-CN** [comment]
fixed in the 1.16+
