### ISSUE TITLE
Armor don't render 

### ISSUE THREAD

**Issue by KizamaruPvP** [Armourers-Workshop/Armourers-Workshop#248]
Hi when I put my custom armor in my wardrobe the armor don't render (The mod is in a server). I have the last version.

**Comment by RiskyKen** [comment]
Please provide a debug crash log. (hold F3 + C for 10 seconds)

**Comment by KizamaruPvP** [comment]
Hi this is the debug crash log https://pastebin.com/dzBtR3Dt

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
