### ISSUE TITLE
[Suggestion] "Frame 0" for bow

### ISSUE THREAD

**Issue by Kickiusz** [Armourers-Workshop/Armourers-Workshop#259]
Minecraft bows have separate texture for an unstrained bow and then 3 frames of straining animation, while the AW skins use first starining frame for an unstrained model. Would it be possible to add an additional "unstrained" frame?

**Comment by SAGESSE-CN** [comment]
imp in next release

**Comment by kkitnetrunner** [comment]
even when making something for Frame 0 it still says I'm missing a marker for frame 0
