### ISSUE TITLE
[BUG] Possible incompatibility with Regeneration mod

### ISSUE THREAD

**Issue by ghost** [Armourers-Workshop/Armourers-Workshop#277]
I have not tested this myself, but [this link describes the issue](https://github.com/Suffril/Regeneration/issues/191)
Basically, Doctor Who Regeneration changes your skin when you die (and also stops you from dying!) But with Armourer's workshop and its skin modification feature as well as models may possibly conflict with new skins, resulting in a steve? skin

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
