### ISSUE TITLE
And betteranimationscollection2  Installation together will crash

### ISSUE THREAD

**Issue by mcmso** [Armourers-Workshop/Armourers-Workshop#285]
https://paste.ubuntu.com/p/sMkRjryBTW/

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

**Comment by mcmso** [comment]
> Sorry, 1.7/1.12 is no longer supported

兄弟你是真敬业啊2019的你还给我关闭了，草
我qq2361004253 以后有问题我直接问你哈哈哈
