### ISSUE TITLE
[BUG]Painted skin on CNPC

### ISSUE THREAD

**Issue by thecrescentkid** [Armourers-Workshop/Armourers-Workshop#292]
Painted skin on cnpc don,t override the skin and bug out ,or state up not work

![2019-10-01_01 45 18](https://user-images.githubusercontent.com/37762002/65940191-7ae39400-e3ed-11e9-9b79-b292b7937601.png)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
