### ISSUE TITLE
[BUG]Another problem of switching the world, armourers doesn't display properly.

### ISSUE THREAD

**Issue by ProperSAMA** [Armourers-Workshop/Armourers-Workshop#297]
**Describe the bug**
I've asked similar questions:
https://github.com/RiskyKen/Armourers-Workshop/issues/290
Recently, I have found that this problem still exists in some cases.
I connected to multiple servers using waterfall. Armourers cannot display normally after transferring to another server. It's basically the same as before.
**To Reproduce**
1. Join the server through waterfall.
2. Teleport to another world, the display is normal.
3. Teleport to another server via waterfall. Armourers cannot be displayed normally.
4. Back to the previous server, armourers cannot be displayed normally.

**Expected behavior**
Armourers should not disappear after teleport to another server.

**Screenshots**
No special screenshot. Same as the previous issue.

**Debug crash log**
https://pastebin.com/AruaVKW9

**Additional context**
Waterfall is similar to bungeeord.
In different servers, config, armorers_workshop and world/skin_database are the same.
There are also some contents in "last.log" this time. It seems the same as before, but I will send it to you.
https://pastebin.com/BywyPUjz

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
