### ISSUE TITLE
[BUG] Hall of Mirrors with Astral Sorcery (+BetterPortals)

### ISSUE THREAD

**Issue by DoomRater** [Armourers-Workshop/Armourers-Workshop#301]
**Describe the bug**
Looking at the horizon with a reskinned Armourer's Workshop item, even one with no fancy blocks, results in a hall of mirrors effect just over the horizon.  The constellations seem to have a faint hall of mirrors effect as well.  Additionally, the sun and moon will produce a hall of mirrors effect when it is raining.

**To Reproduce**
1. Skin an item
2. hold item in hand
3. observe the sky
4. toggle downfall

**Screenshots**
![2019-12-18_20 40 30](https://user-images.githubusercontent.com/4010432/71137931-c8df8b00-21d7-11ea-906e-f4fd5bd57c9f.png)
![2019-12-18_20 40 35](https://user-images.githubusercontent.com/4010432/71137934-cbda7b80-21d7-11ea-9e9b-3ecbb40747dc.png)

**Debug crash log**
https://pastebin.com/tHp9BBZQ

**Additional context**
Armourer's Workshop Version 0.49.1.481 was used for the test.  However, the behavior was also observed on Version 0.49.1.6.
Edit: It turns out that this only occurs when BetterPortals is installed alongside both mods.  A workaround is to use weak rendering in Astral Sorcery's configuration file, but you will not be able to see eclipses if that render is off.

**Comment by DoomRater** [comment]
I recently retested and was unable to reproduce.  The only thing that has changed between the list of mods from before and now is the removal of BetterPortals.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
