### ISSUE TITLE
[BUG] Skins wont load

### ISSUE THREAD

**Issue by Icup2476** [Armourers-Workshop/Armourers-Workshop#306]
Hello, Im unsure if you are still working on amours workshop, but I run a modded minecraft server and use your mod in it. I love the mod and the aspects it brings to the game however there has been an annoying bug that I have to deal with every few months when I either roll back the server or update it. The skins wont load. I have looked inside the skin-database folder in worlds folder to confirm that missing ID is indeed in said folder but it will never render in. This only happens when I am moving files around during a rollback, but it is quite annoying as I have to remake all the skins. Also along witht that note I have tried to take the world file from my server and load it into a single player and it wont load in either. And lastly I tred to change the code that is in the skin-database and put it in the global library, but it does not show up in there (not even a non loading skin). Im very confused as to why this happens as all I am doing when moving files is changing a few things around but not touching the armours files. 

If you need any additional information let me know I would be happy to provide you with it.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
