### ISSUE TITLE
[Feature] Gray out unused dye slots in the Dye Table

### ISSUE THREAD

**Issue by EzerArch** [Armourers-Workshop/Armourers-Workshop#314]
**Is your feature request related to a problem? Please describe.**
Say I'm making a skin set or a outfit, I use a color pallet of 4 dyes. In the helmet I use dye 1 and dye 4; the chest, dye 1 through  4; leggings, dye 2 and 3; and feet, dye 2 and 4.

Fast-forward a few days (or I'm using someone's else skin set), I forget how I made the skins and how many dyes I used. I try to dye the individual skins at the Dye Table, I have to use a bit of trial-and-error to figure out how my color pallet was.

**Describe the solution you'd like**
When you put a skin in the Dye Table, the unused dye slots are grayed out/disabled.

![image](https://user-images.githubusercontent.com/6743303/76659076-3f302700-6554-11ea-9f05-0cf2ebf24cc1.png)

**Describe alternatives you've considered**
None (or better memory XD)

**Additional context**
None.

**Comment by SAGESSE-CN** [comment]
added in 3.0.0 - beta.5
