### ISSUE TITLE
[BUG] [Dev 588] transparent helmets cutting out mannequin head

### ISSUE THREAD

**Issue by DoomRater** [Armourers-Workshop/Armourers-Workshop#317]
**Describe the bug**
Pictures do a better job explaining what's going on here. There's a space helmet in the global library that can be used to double check what's going on.

**Screenshots**
https://imgur.com/a/bYZQ0sB

**Debug crash log**
Sure, why not? https://pastebin.com/KtJzfnVV

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
