### ISSUE TITLE
[BUG] Incompatibility with "Spartan Shields" mod

### ISSUE THREAD

**Issue by DiegoVZ15** [Armourers-Workshop/Armourers-Workshop#328]
The shields of the mod "Spartan Shields" didn't show the skin that i'm using
This image is with a normal shield of minecraft
![2020-05-02_13 07 10](https://user-images.githubusercontent.com/64703176/80872763-aaa39480-8c79-11ea-9e0f-09826c495c0e.png)
And this one is with the Diamond Shield from the mod
![2020-05-02_13 07 36](https://user-images.githubusercontent.com/64703176/80872795-e9394f00-8c79-11ea-9f34-db55d843e4f5.png)

**Comment by RiskyKen** [comment]
What version of the game?
Have you tried added them to the support list?
https://github.com/RiskyKen/Armourers-Workshop/wiki/%5BGuide%5D-Skinning-Modded-Items
