### ISSUE TITLE
[BUG][1.12.2] There is a bug where the preview of clothing items is not visible.

### ISSUE THREAD

**Issue by olmmz** [Armourers-Workshop/Armourers-Workshop#340]
The server is 1.12.2, and I use the latest version "Armourers-Workshop-1.12.2-0.50.5". Item preview is not possible and mannequins are not visible. However, if you wear an invisible item, it will be worn on your character. does anyone has experienced the same phenomenon of me? Sorry for not English well. Please check the screenshot for the phenomenon.
![11](https://user-images.githubusercontent.com/70228674/91208591-6155e400-e745-11ea-8346-8530be678378.JPG)
![22](https://user-images.githubusercontent.com/70228674/91208596-62871100-e745-11ea-8199-3a329af5ff57.JPG)

**Comment by RiskyKen** [comment]
Please post a debug crash, hold F3 + C for 10 seconds.
