### ISSUE TITLE
[BUG]More Player Models issues

### ISSUE THREAD

**Issue by DeerlyAza** [Armourers-Workshop/Armourers-Workshop#341]
When I load up with mpm and armourer's workshop on 1.12.2-0.50.5 it doesnt allow my HD skins to show on my player and none of my saved skins show up. it defaults my skin to the skin i have on without mods.

**Comment by EpicNerd5678** [comment]
I am also having this problem! It's not the biggest deal but it's slightly annoying :(

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
