### ISSUE TITLE
[CRASH]In version 1.7.10-0.48.5, the client will crash and the server will also crash.

### ISSUE THREAD

**Issue by xiaoyanu** [Armourers-Workshop/Armourers-Workshop#342]
**To Reproduce**
Steps to reproduce the crash:
1. Place a square on the ground (this is a box type box)
2. When you right-click to open the box, the client crashes and the server crashes.

Chest：Ender Chest 、 Chest

**Crash log**
Client crash: https://pastebin.com/KmtBwr2h
Server crash: https://pastebin.com/HydHurNK

**Screenshots**
none

**Additional context**
[crash-2020-08-31_10.25.37-server.txt](https://github.com/RiskyKen/Armourers-Workshop/files/5148063/crash-2020-08-31_10.25.37-server.txt)
[crash-2020-08-31_10.19.59-server.txt](https://github.com/RiskyKen/Armourers-Workshop/files/5148064/crash-2020-08-31_10.19.59-server.txt)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

**Comment by xiaoyanu** [comment]
您的邮件我已经收到了~请耐心等待我的回复
