### ISSUE TITLE
[BUG] Inconsistent Quark emote behavior between Armourer's cosmetics and without

### ISSUE THREAD

**Issue by DoomRater** [Armourers-Workshop/Armourers-Workshop#343]
**Describe the bug**
Quark's body rotation along the x axis, the z axis, and all x, y, and z offsets don't translate over to Armourer's Workshop skins.  All other rotations do seem to work, however the y rotation also rotates the arms when Quark's emote system doesn't do so for whatever reason.

**To Reproduce**
0. We need to add this Quark emote to Quark and make sure it's enabled.  None of the default Quark emotes move the body across any dimensions that don't work. https://pastebin.com/pH620ua4 The emote is called "ScrewGravity".
1. Go into third person mode with no armor cosmetics on.  Play the emote and note all the body parts and rotations occurring.
2. Add a full body cosmetic.
3. Repeat step 1 and note the body stays in place.

**Debug crash log**
It's usually requested so here: https://pastebin.com/nyAb1h8n

**Additional context**
Tested with Quark 1.6-179 and Armourer's Workshop 0.50.1.597, but also noticed with 0.50.5

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
