### ISSUE TITLE
[BUG] Item names are shown over the gui

### ISSUE THREAD

**Issue by Catlord-3** [Armourers-Workshop/Armourers-Workshop#345]
**Describe the bug**
Not much to describe here, just shows item names while hovering over the gui if an item is underneath

**To Reproduce**
1. Fill your inventory
2. Click on the armorer
3. open up the options and go to a low slot
4. See name on top of gui

![image](https://user-images.githubusercontent.com/69657737/93821080-e9c78780-fc12-11ea-8186-d62538d5f9c9.png)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
