### ISSUE TITLE
Convert player skins to Skin Block constructions [Feature]

### ISSUE THREAD

**Issue by PTVoltz** [Armourers-Workshop/Armourers-Workshop#346]
In short: is it possible to add a button to the armorer that converts the main section of a player skin (though probably not overlays) into solid Skin Blocks that can be edited while Part Overrides are on?
I've been trying to do some additions for my MC Skin involving inset sections (specifically having hollow parts inside the arm and three layers deep of blocks in the chest area), which requires Overrides to be on, however I'd rather not have to rebuild the unedited parts of the body, arm etc block by block.
Plus it would add a way for players to save block statues of their MC Skins, which is also nice.

**Comment by SAGESSE-CN** [comment]
i think this is not a necessary feature, and considering possible legal reasons. so reject it.
