### ISSUE TITLE
[BUG]outfits disapear on npc after rejoining world

### ISSUE THREAD

**Issue by FyrfyX8** [Armourers-Workshop/Armourers-Workshop#352]
**Describe the bug**
when i rejoin my world the outfits and other skins on my npc disapear

**To Reproduce**
1. Give a npc a skin or outfit
2. Go back to the menu
3. rejoin world

**Expected behavior**
that the outfits dont disapear

**Screenshots**

**Debug crash log**
Linking a debug crash log can help track down bugs. Holding down F3 + C for 10 seconds in game will force the a crash making a debug crash log. Please link your log using a site like https://pastebin.com/

**Additional context**

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
