### ISSUE TITLE
[BUG]  flashing skin

### ISSUE THREAD

**Issue by Traftyy** [Armourers-Workshop/Armourers-Workshop#353]
I found this bug the skins I use are flashing like that and this bad to play has any solution?
![bug aw](https://user-images.githubusercontent.com/76985508/103605660-42394100-4ef3-11eb-8a27-ac6b64cea6e2.png)

**Comment by Traftyy** [comment]
Armourers-Workshop-1.7.10-0.48.5

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
