### ISSUE TITLE
[BUG] Mannequins can flood areas with their own drops

### ISSUE THREAD

**Issue by DoomRater** [Armourers-Workshop/Armourers-Workshop#354]
**Describe the bug**
Mannequins can occasionally be found with their mannequin's item flooded around it when coming back to an aera that hasn't been loaded in a while.  The flood of items is massive, filling multiple double chests easily.

Last seen on AW 0.51.0 on a server.  I have not reproduced this in a single player instance personally.

**To Reproduce**
Reproduction is inconsistent, but perhaps the screenshot can demonstrate some instances where the bug might reproduce more easily.  It seems to happen more often when a mannequin just slightly clips into another block.

**Screenshots**
![2021-01-11_18 08 23](https://user-images.githubusercontent.com/4010432/104249221-f9c0dc80-5438-11eb-8d06-20c48ab9b17d.png)

**Comment by yirip** [comment]
It happens in my server as well. All the skinned mannequins will duplicate itself and drop all the skins it had. I feel like it is somehow related to chunk loading, because it does not happen when I’m looking at it. It occurs when I leave the site and come back a while later.

**Comment by yirip** [comment]
Right after I rebooted my server:

![2021-03-03_09 21 40](https://user-images.githubusercontent.com/47721566/109828506-4e473380-7c02-11eb-8b03-58a2418b9755.png)
![2021-03-03_09 21 33](https://user-images.githubusercontent.com/47721566/109828507-4e473380-7c02-11eb-8181-f00397554a3e.png)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

If it still in the 1.16+, reopen it
