### ISSUE TITLE
[BUG]Outfit covered by the skin

### ISSUE THREAD

**Issue by oPpGgG** [Armourers-Workshop/Armourers-Workshop#355]
I painted the outfit directly on the skin, then I directly equip the outfit it was all OK. However, when I attach the outfit on the armor and then put it on, the outfit just covered by the skin.Im sure my setting was all right.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

And if issue still in the 1.16+, please reopen it
