### ISSUE TITLE
Don't let me take out the clothes on the mannequin.

### ISSUE THREAD

**Issue by HongMint88** [Armourers-Workshop/Armourers-Workshop#360]
If you're not a manager, you shouldn't let the mannequin wear out. Why the hell isn't this functioning? Isn't the mannequin for display?

**Comment by SAGESSE-CN** [comment]
I do not quite understand what you needs

**Comment by SAGESSE-CN** [comment]
your can change the entity attribute in the 1.16+, 1.7/1.12 no longer supported.
