### ISSUE TITLE
[BUG] In the 1.7.10 version going into F5 or around other players lowers my FPS to around 30

### ISSUE THREAD

**Issue by brandyyn** [Armourers-Workshop/Armourers-Workshop#362]
In the latest 1.7.10 version, 0.48.5, going into F5 or around other players lowers my FPS to around 30 in my modpack. This is not an issue without the mod. I also tested 0.47.1 and it's the same story. I haven't tested the 1.12 versions because my pack isn't in 1.12. This is the best example I have, of when I didn't know what was causing the issue. https://www.reddit.com/r/feedthebeast/comments/mavmhm/low_fps_when_in_f5_or_looking_at_other_players/

**Comment by brandyyn** [comment]
@RiskyKen  :(

**Comment by brandyyn** [comment]
![image](https://user-images.githubusercontent.com/11356565/204947958-5d8a2cf8-d16f-4400-899b-71e9d4b83e57.png)
![image](https://user-images.githubusercontent.com/11356565/204947975-20f6f991-ef7c-4603-a643-2f83778fde23.png)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

**Comment by brandyyn** [comment]
> Sorry, 1.7/1.12 is no longer supported

if you took one minute to read the post, not only did i post the solution and fix but i also closed the issue!

**Comment by SAGESSE-CN** [comment]
yep, i know.
