### ISSUE TITLE
[CRASH] A phenomenon in which error messages are repeated indefinitely on a bukkit.

### ISSUE THREAD

**Issue by HongMint88** [Armourers-Workshop/Armourers-Workshop#364]
**To Reproduce**
Steps to reproduce the crash:
1. Occurs continuously from when the server opens until it turns off.
2. Error message only in bukkit.

**Crash log**
[https://pastebin.com/kaERra4Z](https://pastebin.com/kaERra4Z)

**Comment by Wanako0609** [comment]
Yes I have the same problem. Have you found the solution ?

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
