### ISSUE TITLE
[BUG] Colored Skin Blocks look invisible. 1.12.2 BETA

### ISSUE THREAD

**Issue by FelisMoon** [Armourers-Workshop/Armourers-Workshop#366]
When saving armor creations, all colored skin blocks are invisible for me. They do not show up in the inventory slots, neither while equipped. Skin blocks that are not painted do render fine though, as well as the head override and the second layer disabled. 

This only happens with new creations, Official creations included in the mod can be loaded and rendered without any issues.

Im not sure how to reproduce it, but this happens to me with the mod completely alone and Optifine. 

Id expect the mod to save all skin blocks painted as i pleased, (Painted em all only with the brush tool)
![2021-08-07_12 40 31](https://user-images.githubusercontent.com/81988520/128605741-af9097b2-94b4-4a80-8cb9-5e11b0889c54.png)

![2021-08-07_12 41 05](https://user-images.githubusercontent.com/81988520/128605752-63c9a2b7-d69a-4c08-a636-0aaead871212.png)

**Comment by AzzyOliver** [comment]
When picking a color , don't leave the Paint Type at none, or else it wont show up

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
