### ISSUE TITLE
[BUG]Skin does not appear in the Global Skin Library.

### ISSUE THREAD

**Issue by RIJATV** [Armourers-Workshop/Armourers-Workshop#367]
**Describe the bug**
When I right-click on a global skin library block, the skin should appear, but when I click join, [Java 8 Update 51] pops up as My Java and causes a bug. My Java version is [Java 8 Update 291] and I also tried [Java 8 Update 301] but failed. I have used this mode with other modes. It was good at first, but there was an error with other modes, so I erased other modes and opened the library block of this mode, and this error occurred. I erased this mode and tried to install it, but it failed.

I saw the video here. And I followed the way in this video. However, while playing the game, the connection to the game is terminated, causing a bug. Is there any other solution?

![image](https://user-images.githubusercontent.com/88968738/129476618-db780a18-d8d1-4ef7-b227-3409111f68fa.png)
![image](https://user-images.githubusercontent.com/88968738/129476628-b9603889-239e-4c0c-948d-4ed0ac499ba8.png)

-This error has been in this state for a long time.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

And not a bug, you need change java version in the minecraft launcher
