### ISSUE TITLE
Problem :(

### ISSUE THREAD

**Issue by Set775** [Armourers-Workshop/Armourers-Workshop#371]
Hi, I'm from Russia (I use a translator) and I have such a problem when I have a breastplate (it doesn't matter if a skin is attached to it or it's just an outfit) then all the things in my hand are displayed as if in the middle of the body, that is, if I take a sword, it seems to "pierce" me. What is the problem?

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported, and not any valid information
