### ISSUE TITLE
[CRASH]I can't join my world when I load Armourer's Workshop and the TFC at the same time

### ISSUE THREAD

**Issue by Sakuranokwa** [Armourers-Workshop/Armourers-Workshop#373]
I can't make sure of the reason , it may a FallingeEntity , like a sand in TFC .
Our  server will crash if I load Armourer's Workshop and the TFC at the same time and join a world , it will crashes after a few of seconds ;
But if i do the same in a clent , the crash didn't happen at all .
Please solve the crash if you have some time enought .
[Up loading crash-2021-12-03_21.53.01-server.txt…]()

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
