### ISSUE TITLE
[BUG] Skins are not showing up when I put them on.

### ISSUE THREAD

**Issue by WizardPlaysMC** [Armourers-Workshop/Armourers-Workshop#376]
The skins I make or download on Armourer's Workshop do not appear when I put them on. They appear in my inventory and on mannequins, though.

Mods I'm using:
![Mods](https://user-images.githubusercontent.com/104698285/166123610-1554ca5f-1321-4911-a543-92f56ed4ac0b.png)

I'm trying to create an RP in Minecraft so I need the skins to show up.

**Comment by DoomRater** [comment]
I don't see Obfuscate in there, but I thought Ido recently changed over to require that library. Are you sure you don't have it in your pack?

**Comment by WizardPlaysMC** [comment]
> Obfuscate

I never said I had Obfuscate in my modpack. I'm just saying that Armourer's Workshop is not showing any of the custom skins I create when I wear them. I only showed a list of mods so that I could find out if any of them may have played a role in this bug.

**Comment by DoomRater** [comment]
So I double checked Ido's dependencies and it is clear they do not use it.  However...
https://github.com/Kaydax/Ido/issues/2
We can see it does funny stuff with RenderPlayer which is likely interfering.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
