### ISSUE TITLE
The wings and the objects don't appear on my skin. Only in wardrobe.

### ISSUE THREAD

**Issue by joaninitv** [Armourers-Workshop/Armourers-Workshop#377]
I have a 1.12.2 server with magma and I have around 70 mods. I can see the wings in the wardrobe but later in the skin, doesn't appear, and the others can't see either.

Here you have the screenshots

![2022-06-05_11 55 23](https://user-images.githubusercontent.com/91762553/172045152-aa6fb685-c7e5-48d1-ae36-fbe7edbe9aa6.png)

![2022-06-05_11 55 35](https://user-images.githubusercontent.com/91762553/172045156-10278f84-4915-4c3d-8b39-a21defd520c2.png)

I don't know how to solve this. If you want, I could say you which mods are in the mod pack.

I would like to fix it as soon as possible

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
