### ISSUE TITLE
[BUG] When ever i put the stuff i made on inside my wardrobe it dosent show up and when i press f5 i cant see it on me?

### ISSUE THREAD

**Issue by FinlayTheAxolotl** [Armourers-Workshop/Armourers-Workshop#380]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug crash log**
Linking a debug crash log can help track down bugs. Holding down F3 + C for 10 seconds in game will force the a crash making a debug crash log. Please link your log using a site like https://pastebin.com/

**Additional context**

**Comment by FinlayTheAxolotl** [comment]
![Capture](https://user-images.githubusercontent.com/109169083/178552326-6d3ccfae-9355-4b43-9df3-f9b559fe7414.PNG)
look at this i cant even see what im wearing when i put my armour on also i keep getting this warning someone pls help?

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
