### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by XenossoneX** [Armourers-Workshop/Armourers-Workshop#381]
**Please someone answer the question.**

Is it possible in any way to place a certain skin on the server so that it is displayed in the menu GUI or, for example, in random boxes? If yes, who in what way? What data needs to be specified in order for a specific skin to start displaying in the plugins GUI?

Thanks in advance! You will help me a lot!

**Comment by SAGESSE-CN** [comment]
You need to attach the skin to the item, and then display the item in a menu.
