### ISSUE TITLE
Remove Outfit

### ISSUE THREAD

**Issue by odamarzito** [Armourers-Workshop/Armourers-Workshop#382]
be able to remove the outfit mode and receive the aws used to create the outfit

**Comment by SAGESSE-CN** [comment]
for what purpose?

**Comment by odamarzito** [comment]
> for what purpose?

sometimes you need the separate aw for something, maybe modify and there's no way to undo the outfit

**Comment by SAGESSE-CN** [comment]
for to my observation, this feature will not bring positive results to aw.

if you are the author of outfit, you not need an undo feature.

If you not author of the outfit, then disassemble other people's fit without the author's authorization, this is not what we want.
