### ISSUE TITLE
[CRASH] CLIENT CRASH ON SERVER When using "Armourer", "Global/Skin Library" Block or any type of block that has a gui

### ISSUE THREAD

**Issue by yahi-ko** [Armourers-Workshop/Armourers-Workshop#383]
**To Reproduce**
Steps to reproduce the crash:
1. Create a server for Forge 1.18.2 and put the Armourer's Workshop Mod
2. After joining the server, use any block and the crash will happen.

Forge: 40.1.80
Version: 1.18.2

**Crash log**
https://pastebin.com/wtMxg5rH

**Screenshots**

**Additional context**
I already tested the mod on singleplayer and it works fine even with rubidium. But, when using it in a server, the client crashes but for some reason the server is still online.

**Comment by RiskyKen** [comment]
@yahi-ko Do not assign random people.

**Comment by SAGESSE-CN** [comment]
```

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.server.permission.handler.IPermissionHandler.getRegisteredNodes()" because "net.minecraftforge.server.permission.PermissionAPI.activeHandler" is null
    at net.minecraftforge.server.permission.PermissionAPI.getOfflinePermission(PermissionAPI.java:87) ~[forge-1.18.2-40.1.80-universal.jar%2370!/:?] {re:classloading}
    at moe.plushie.armourers_workshop.compatibility.forge.AbstractForgePermissionManager$1.resolve(AbstractForgePermissionManager.java:53) ~[armourersworkshop-forge-1.18.2-2.0.0-beta.1.jar%2353!/:?] {re:classloading}
```
1. try use forge server only
2. if 1 is successly report to rubidium

**Comment by yahi-ko** [comment]
tried with Armourer's workshop only on both client & server
crash report from client: https://pastebin.com/Vb56ztES
it didn't crash the server but I can give you the latest log
I don't think it would be of any help tho. but here is the latest log of the server: https://pastebin.com/Sgtp7abR)

**Comment by SAGESSE-CN** [comment]
Fixed, retry this version https://www.curseforge.com/minecraft/mc-mods/armourers-workshop/files/4057618

**Comment by yahi-ko** [comment]
Thanks! it's fixed now!

**Comment by ruslantelicin44-cmd** [comment]
привет все кто знает как исправить проблему что оружейный стол на версии 1.16.5. неработает . вернее не создает объект. а на  креативе создает.
