### ISSUE TITLE
[BUG] Only one 3D model visible, others are transparent

### ISSUE THREAD

**Issue by TheCanterlonian** [Armourers-Workshop/Armourers-Workshop#384]
When i wear more than one 3D item, only one of the models appears in the world. This is also true for dual model items like wings, only one wing will render correctly if i only wear wings. It only does this in the world and not in the GUI. Images are attached. It happens for players and for mannequins.

**To Reproduce**
1. hit P
2. put any two 3D models on
3. exit the GUI

**Expected behavior**
i expected to see the items rendered on my player character.

**Screenshots**
https://imgur.com/a/nDl8tkq

**Debug crash log**
https://pastebin.com/C0sy3DWk

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported

**Comment by TheCanterlonian** [comment]
how do i check which versions are supported?

**Comment by TheCanterlonian** [comment]
i ask because 1.12 is the latest version on the readme file

**Comment by TheCanterlonian** [comment]
is there at least a version on curseforge that worked at the time on 1.12 or are all of them broken? should i just test every 1.12 file on curseforge if i want to use an old version?
