### ISSUE TITLE
[CRASH] when opening the global skins library (1.7.10)

### ISSUE THREAD

**Issue by kotmatross28729** [Armourers-Workshop/Armourers-Workshop#385]
**To Reproduce**
Steps to reproduce the crash:
1. open the global skins library
2. click show all
3. scroll through 5-10 pages
4. get crash

**Crash log**
https://pastebin.com/hAA3hV4F

**Comment by RiskyKen** [comment]
Do not assign random people.

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
