### ISSUE TITLE
[Feature] No need Mod ( Accept Vanila Player )

### ISSUE THREAD

**Issue by mocxlbor** [Armourers-Workshop/Armourers-Workshop#386]
**Is your feature request related to a problem? Please describe.**
need fix Please install correct Armourers Workshop to play on this server!

**Describe the solution you'd like**
Accept Vanila Player Featrue

**Describe alternatives you've considered**
No

**Additional context**
Pls Fix Please install correct Armourers Workshop to play on this server! ( i need use Polymc Porter )

**Comment by SAGESSE-CN** [comment]
pls don't change the mod name in the older version, and 1.7/1.12 is no longer supported
