### ISSUE TITLE
[Feature] Please support Curios API on higher version (1.18.2)

### ISSUE THREAD

**Issue by Sam-Chai** [Armourers-Workshop/Armourers-Workshop#387]
**Is your feature request related to a problem? Please describe.**
No, just add a curios support for armourers workshop.

**Describe the solution you'd like**
Players could use them skins on curios slot

**Describe alternatives you've considered**
armourers workshop's own skin menu, 

**Additional context**
But the official skin menu didn't support curios, and it seems like not compatible with curios (dont crash, but not display curios's armor)

**Comment by SAGESSE-CN** [comment]
release in the next version
