### ISSUE TITLE
[BUG] When a vax is summoned near the player, a crash occurs. (ver 1.19.3)

### ISSUE THREAD

**Issue by Khalid02211** [Armourers-Workshop/Armourers-Workshop#389]

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/216520196-8900d895-36b0-4a84-ae27-ee515491f6e3.png">

we can't to reproduce this crash, please provide the log file.

**Comment by SAGESSE-CN** [comment]
please reopen after providing more information.
