### ISSUE TITLE
[BUG] Colored blocks are invisible after saving a build to an item

### ISSUE THREAD

**Issue by gruniu8** [Armourers-Workshop/Armourers-Workshop#390]
I place the armourer, build something and after saving only the uncolored blocks appear, i've tried this on singleplayer and multiplayer on 1.19.2 (skins downloaded from global skin library works)

**Comment by gruniu8** [comment]
and i forgor to say i'm playing on forge 43.2.4

**Comment by SAGESSE-CN** [comment]
Fix in beta.14
