### ISSUE TITLE
Hey guys, Do you know how to solve this problem?

### ISSUE THREAD

**Issue by Marksxerons2** [Armourers-Workshop/Armourers-Workshop#394]
I'm creating a server But I'm having this problem, I put on clothes, and when I pick up a sword, it stays on my belly, not in my hand, how can I solve it?

![como resolver](https://user-images.githubusercontent.com/127993030/225431597-7e57835f-938e-481f-8217-7678c453a10f.png)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported
