### ISSUE TITLE
[Feature] Better Combat and First-person Model compatibility?

### ISSUE THREAD

**Issue by nikoraasu** [Armourers-Workshop/Armourers-Workshop#395]
**Is your feature request related to a problem? Please describe.**
Using both the mods creates visibility problems, for example when wearing a helmet, when you attack it goes in your way.

**Describe the solution you'd like**
I know that there already are overrides that turn off helmet rendering but they do not work when both mods are turned on.
I think an option to not render the armor (or at least the helmet) for the user would be ideal. That way when attacking when using First Person model and Better Combat at the same time, nothing is gonna get in the way. 

**Describe alternatives you've considered**
Not rendering the armor is the only simple solution that I can think of, so no alternatives.

**Comment by SAGESSE-CN** [comment]
sorry, but the `Better Combat` incompatibe `First-person Model`, i don't know what we can do.
