### ISSUE TITLE
[BUG] itemSkinnable does not work (Fabric 1.18.2)

### ISSUE THREAD

**Issue by nikoraasu** [Armourers-Workshop/Armourers-Workshop#396]
**Describe the bug**
to command to set item skinnable does not work

**To Reproduce**
1. Equip an item you would like to set skinnable (any sword in my case)
2. use the /armourers itemSkinnable add sword command

**Expected behavior**
The item becomes skinnable and gets a model that I have equipped in my Armourer's Workshop inventory

**Additional context**
This does not work with any items - vanilla, modded.
Also tried without any mods and just with armourer's workshop, and doesn't work either.

**Comment by SAGESSE-CN** [comment]
I noticed this issue, but unfortunately I can't reproduce it. maybe or related to windows.

**Comment by nikoraasu** [comment]
i am not on windows, I am on linux

**Comment by SAGESSE-CN** [comment]
@nikoraasu this issue still exist in the latest version?

**Comment by SAGESSE-CN** [comment]
If it is still a problem with the latest version, please open it again at any time.
