### ISSUE TITLE
[CRASH] Attempting to edit overrides in 1.16.5 crashes game

### ISSUE THREAD

**Issue by VanguardDawn** [Armourers-Workshop/Armourers-Workshop#398]
**To Reproduce**
Steps to reproduce the crash:
1. Go to 'Mods'
2. Click on 'Armourer's Workshop', click Config
3. Navigate to 'Common Configurations'
4. Navigate to 'Overrides'
5. Click 'Edit' on 'Item Overrides'
6. Watch it try to tell you 'Saving world...' when you're on the main menu
7. Ask yourself what just happened as it crashes

**Crash log**
[Available here.](https://pastebin.com/tEJ1amYp)

**Additional context**
I am also using the Configured mod. The modifications to overrides work as intended when edited in Notepad++, and while this file doesn't list tridents as a valid override, they do function fine.

**Comment by SAGESSE-CN** [comment]
`java.lang.Boolean cannot be cast to java.lang.String`

your config is bad

**Comment by VanguardDawn** [comment]
Not really sure what that means. Is that something I can fix?

**Comment by SAGESSE-CN** [comment]
upload your config

**Comment by VanguardDawn** [comment]
[Got it right here.](https://pastebin.com/MHbTZ6t5)

**Comment by SAGESSE-CN** [comment]
or remove the itemOverrides

**Comment by VanguardDawn** [comment]
It was crashing before I added the itemOverrides. That's how I got the idea to edit them in Notepad++ (unaware that there's a command to do that).

**Comment by SAGESSE-CN** [comment]
when armorers_workshop-common.toml save action will sync to the game immediately, if you modify it by mistake, it will crash the game

Commands:
`/armourers itemSkinnable sword add`

**Comment by SAGESSE-CN** [comment]
`com.mrcrayfish.configured.impl.ForgeValue.isValid` are you using a third party for config?

**Comment by VanguardDawn** [comment]
Yeah, I'm using a mod called Configured. Is that the cause of the crash? Wouldn't be the first time I've had issues with Armourer's and a MrCrayfish mod.

**Comment by SAGESSE-CN** [comment]
Incompatible for Configured

**Comment by VanguardDawn** [comment]
Should those be added to the list of known incompatibilities? So far only Obfuscate and the third-party TLauncher are listed there.

**Comment by SAGESSE-CN** [comment]
not, the obfuscate is compatible in the 1.16+, Configured is new issue, i will fix it later

**Comment by SAGESSE-CN** [comment]
fix in next version

**Comment by SAGESSE-CN** [comment]
released in 2.0.0-beta.19
