### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by LixoGamer29** [Armourers-Workshop/Armourers-Workshop#400]
**Problem**
The mod is not compatible with the latest versions of Forge for 1.16.5.

**Solution**
Request for an update to be made so that the mentioned mod can be used in the version 1.16.5 - 36.2.35.

**Additional context**
I need to use the mentioned version of Forge to use Optifine(Optifine is an important mod for optimizing modpacks, but it is not compatible with older versions of Forge.), but the mod armourers workshop is not compatible with new versions of Forge, leading them to make the update request. It is important to emphasize that the request is for an update of the mod to the specific versions of Forge mentioned and not for new versions of the game.

**Comment by SAGESSE-CN** [comment]
the forge last version is 36.2.39, optifine is compatible this version

**Comment by SAGESSE-CN** [comment]
required forge down to 36.3.21
