### ISSUE TITLE
[BUG] RT shader not working

### ISSUE THREAD

**Issue by ShenxPresent** [Armourers-Workshop/Armourers-Workshop#401]
**Describe the bug**
shadow incorrect when use PTGI in 1.16.5

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53565917/236433317-662032f6-fe6b-4072-940e-1f69addb7f7a.png)

**Debug crash log**
no crash

**Additional context**
It seems that someone can ust PTGI with correct shadows, but no details. https://tieba.baidu.com/p/6900586120

**Comment by SAGESSE-CN** [comment]
the link aw is 1.12

**Comment by ShenxPresent** [comment]
> the link aw is 1.12

It seems like that everything in this mod is rendering the same way of the first person hand? maybe using terrain or entity render could fix this issue while most shader are not compile with the first person hand shadow rendering.

**Comment by ShenxPresent** [comment]
> the link aw is 1.12

another finding is that it used PTGI e7, but there's still an issue that most shader are not work correctly.

**Comment by ShenxPresent** [comment]
> the link aw is 1.12

another finding is that it used PTGI e7, but there's still an issue that many shaders are not work correctly.

**Comment by ShenxPresent** [comment]
> 链接 aw 是 1.12

Finding that is the incorrect normal culculate, I am trying to fix it in shader pack

**Comment by ShenxPresent** [comment]
It seems like that the bug is mainly caused by the incorrect tbn culculation, which means there's maybe some issue on the texcoord.

**Comment by ShenxPresent** [comment]
Fine... Now here's a solution, it seems like that the tbn could make the viewnormal out of range(-1,1), which I thought could be fixed by the mod side, if this could be fixed it seem like better than waiting for all shader add clamp function during culculating normal in view space.

**Comment by SAGESSE-CN** [comment]
i need more details, possible in [qq](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=o2L0-5lABPgFum97lC4nXmtW5TMZ_R76&authKey=HIGluqp1xWMAjPKc5%2BZ7SMh5PwIY%2FhZildDCWCcmoAovnBfGw%2B%2FpIiLapE50Y7m%2F&noverify=0&group_code=540297010) or [discord](https://discord.gg/5Z3KKvU) to discuss?

**Comment by ShenxPresent** [comment]
> i need more details, possible in [qq](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=o2L0-5lABPgFum97lC4nXmtW5TMZ_R76&authKey=HIGluqp1xWMAjPKc5%2BZ7SMh5PwIY%2FhZildDCWCcmoAovnBfGw%2B%2FpIiLapE50Y7m%2F&noverify=0&group_code=540297010) or [discord](https://discord.gg/5Z3KKvU) to discuss?

sure, I have send my request to join your qq group.

**Comment by SAGESSE-CN** [comment]
fixed in next release
