### ISSUE TITLE
[Feature] PBR for glowing cube.

### ISSUE THREAD

**Issue by ShenxPresent** [Armourers-Workshop/Armourers-Workshop#402]
**Is your feature request related to a problem? Please describe.**
glowing blocks cannot glow in shaders who use blockID as lighting reference.

**Describe the solution you'd like**
let glowing blocks can light when using shader.

**Describe alternatives you've considered**
I think it is good idea that give glowblock an extra texture "glowcube" rather than share the same texture "cube" with others so that we can use pbr to make the thing.

**Additional context**

**Comment by SAGESSE-CN** [comment]
released in 2.0.0-beta.19
