### ISSUE TITLE
[BUG] Idk if this is a bug but i can't find a lot of items like global skin library (Forge 1.16.5)

### ISSUE THREAD

**Issue by Nxtsuvv** [Armourers-Workshop/Armourers-Workshop#404]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug crash log**
Linking a debug crash log can help track down bugs. Holding down F3 + C for 10 seconds in game will force the a crash making a debug crash log. Please link your log using a site like https://pastebin.com/

**Additional context**

**Comment by SAGESSE-CN** [comment]
mod list？

**Comment by Nxtsuvv** [comment]
> My mod list is Armour's Workshop
Appleskin
Alex's Mobs
BiomesOPlenty
carry on
Chaos Awakens
citadel
Farts
Geckolib
Gravestone
Hole Filler
Ice And Fire
Immersive Paintings
Jade/Hwyla
InventoryPets
jei
Journeymap
Mowziesmobs
Optifine
ProjectE
Refined Storage
Serene Seasons
Sophisticated Backpacks
Waystones 
Wings

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/6c1659b7-8d36-4ad4-8350-3fb87ebab265">

**Comment by Nxtsuvv** [comment]
Strange i didn't found so i tried to remove mod and download again, Worked!
