### ISSUE TITLE
[BUG] Ping to HIGH

### ISSUE THREAD

**Issue by itmylight** [Armourers-Workshop/Armourers-Workshop#405]
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/49058689/e7bfa7f8-c195-4fb3-b9ff-88afd1bd9df9)

on Join the server
its Make ping player to high

**Comment by SAGESSE-CN** [comment]
version？ and first join will download skin, besides we not any changes of the network usage

**Comment by itmylight** [comment]
armourersworkshop-forge-1.16.5-2.0.0-beta.17
every time when a player joins,
can I solve this problem?
I just install it on the server, I haven't downloaded any skins yet.

**Comment by SAGESSE-CN** [comment]
This has nothing to do with aw, you need to check other mods
