### ISSUE TITLE
Unable to display special blocks correctly[BUG]

### ISSUE THREAD

**Issue by Jestor1966** [Armourers-Workshop/Armourers-Workshop#406]
**Describe the bug**

When this mod is enabled on the Fabric server in 1.19.2, special blocks such as Bed and Item Frame will not be displayed correctly(Including the item texture of the bed). These blocks are likely rendered inside the armourers(as shown in the picture).

![text](https://img1.imgtp.com/2023/05/30/218hxI6g.png)

**Versions**

Minecraft: 1.19.2
Fabric : 0.14.19
Fabric API : 0.76.0+1.19.2
Fabric Loader : fabric-loader-server-0.14.20
Armourers-Workshop : v2.0.0-beta.21

**Comment by SAGESSE-CN** [comment]
i need more details, possible in [qq](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=o2L0-5lABPgFum97lC4nXmtW5TMZ_R76&authKey=HIGluqp1xWMAjPKc5%2BZ7SMh5PwIY%2FhZildDCWCcmoAovnBfGw%2B%2FpIiLapE50Y7m%2F&noverify=0&group_code=540297010) or [discord](https://discord.gg/5Z3KKvU) to discuss?

**Comment by Jestor1966** [comment]
> i need more details, possible in [qq](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=o2L0-5lABPgFum97lC4nXmtW5TMZ_R76&authKey=HIGluqp1xWMAjPKc5%2BZ7SMh5PwIY%2FhZildDCWCcmoAovnBfGw%2B%2FpIiLapE50Y7m%2F&noverify=0&group_code=540297010) or [discord](https://discord.gg/5Z3KKvU) to discuss?

yeah no problem.
