### ISSUE TITLE
[BUG]compatibility issue with Curtain(a Forge mod like fabric-carpet)

### ISSUE THREAD

**Issue by ghost** [Armourers-Workshop/Armourers-Workshop#409]
**Describe the bug**
The world will become unresponsive if you use the /player command which is added by [Curtain](https://www.curseforge.com/minecraft/mc-mods/curtain) Mod to summon a fake player

**To Reproduce**
1.Install curtain
2.use command: /player (playername) spawn to spawn a fake player
3.The world has no response to player's actions,the game tick seems to be "frozen"
 
Having reported to Curtain team.    https://github.com/Gu-ZT/Curtain/issues/83

**Comment by SAGESSE-CN** [comment]
curtain的问题

**Comment by SAGESSE-CN** [comment]
fixed in next release
