### ISSUE TITLE
[BUG] Disable Recipe not working

### ISSUE THREAD

**Issue by KLONOA9X6** [Armourers-Workshop/Armourers-Workshop#410]
**Describe the bug**

**To Reproduce**
1. Set 'disableRecipes' option to false
2. Restart the server
3. Craft any item of Aromurer's Workshop

**Expected behavior**
Item in Aromurer's Workshop will not craftable.

**Screenshots**
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/95112579/9b83aeb9-465e-49c6-9645-a7763c0c2abe)

**Debug crash log**
_No Response_

**Additional context**
Mod Version: 2.0.0-beta.24
Minecraft Version: 1.19.2
Fabric Version: 0.14.19
Fabric-API Version: 0.76.0

**Comment by SAGESSE-CN** [comment]
yep, you need using other modes or datapack to manage recipes

**Comment by SAGESSE-CN** [comment]
aw uses a normal data pack to implement recipes, which may be a problem with kubejs

**Comment by SAGESSE-CN** [comment]
https://github.com/Armourers-Workshop/Armourers-Workshop/blob/develop/common/src/main/resources/data/armourers_workshop/recipes/items/skin-unlock-chest.json

**Comment by KLONOA9X6** [comment]
oh, crap.
