### ISSUE TITLE
[BUG] Transparent Blocks

### ISSUE THREAD

**Issue by Grusalho** [Armourers-Workshop/Armourers-Workshop#411]
When i put any blocks at the map he get this glitched texture

![imagem_2023-06-28_222453855](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/138080426/f8dd4e4a-b9e0-4da7-9c7c-5b0047045bad)

Just a single example, but it happens with all blocks.

I play at 1.19.2 fabric server

**Comment by SAGESSE-CN** [comment]
mod version? and the disabled shader it work normal?

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/8c4a9e0e-5c6f-4efe-ac17-18c7d6c92c5a">

**Comment by Grusalho** [comment]
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/138080426/d06e84e6-142d-4ad8-80a4-6d0292f0861c)
Shader On
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/138080426/184bf2a4-496d-4799-99dd-76f1e0a454fa)
Shader Off


Mod Version : 
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/138080426/66e52b19-d291-42cb-9568-dbc4df868096)

**Comment by SAGESSE-CN** [comment]
reopen if not fixed
