### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UlSheep** [Armourers-Workshop/Armourers-Workshop#412]
The Equipment Cube are not colored correctly unless sodium mod is uninstalled.
version: minecraft 1.20
![螢幕擷取畫面 2023-06-30 223953](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/136002981/17b4662c-3553-4d5b-aada-21fb3752da32)

**Comment by SAGESSE-CN** [comment]
pls provied mod list

**Comment by UlSheep** [comment]
My shader mods:
iris-mc1.20-1.6.4
sodium-fabric-mc1.20-0.4.10+build.27
indium-1.0.18mc1.20

!! and when I set Video setting /quality /biome blend into 0 ,Equipment Cube show correctly(I try all setting to find this :))
![螢幕擷取畫面 2023-07-01 195234](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/136002981/19ffeac9-6f9a-4ada-a5f0-794611e5e563)
![螢幕擷取畫面 2023-07-01 195040](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/136002981/071ef5f4-4e1a-4e6e-a798-1a05b8eb1e36)

**Comment by SAGESSE-CN** [comment]
Yes, we don't support sodium's biome blend, and we don't know how to support it. a bigger problem is that shader mod/pack will cause the cube color to infuse, so never use the shader mod/pack when make skin.

**Comment by SAGESSE-CN** [comment]
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/921c302a-4c5c-4a9f-b91e-210fdc2418d1)
