### ISSUE TITLE
[BUG] (Fabric 1.16.5) armourers workshop requires a wrong fabric api

### ISSUE THREAD

**Issue by IBeiKui** [Armourers-Workshop/Armourers-Workshop#413]
**Describe the bug**
Fabric armourers workshop mod require Fabric API. But I found it need Fabric API whose id is "fabric-api". However the id of Fabric API in 1.16.5 is "fabric". And it made the game can't be launched.
(Sorry I use translator, there might be some gammer errors)
**To Reproduce**
1. download the latest Fabric API mod(fabric-api-0.42.0+1.16) and put it into mods folder
2. download the latest Armourers-Workshop(armourersworkshop-fabric-1.16.5-2.0.0-beta.28) mod and put it into mods folder
3. Fabric pops out a window telling me that the game is unable to be launched.

**Expected behavior**
Fix the little error

**Screenshots**
![Screenshot-2023/7/3](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/50074117/969fbec5-15a9-497e-bfca-0aca3562251c)

**Debug crash log**

[latest.log](https://github.com/Armourers-Workshop/Armourers-Workshop/files/11933353/latest.log)

**Additional context**

**Comment by SAGESSE-CN** [comment]
https://github.com/Armourers-Workshop/Armourers-Workshop/releases/tag/v2.0.0-beta.29
