### ISSUE TITLE
[BUG] A bug where the bow frame of armorers workshop bow modeling is not applied

### ISSUE THREAD

**Issue by CreamWorldGit** [Armourers-Workshop/Armourers-Workshop#414]
There is a bug that the bow frame (motion) of Armorer Workshop bow modeling is not applied and applied as normal Minecraft bow motion(none of change by motion).
This bug has been occured from Armorer's Workshop Ver. 2.0.0-beta.28

Additional context
Version 1.19.2
Forge Ver. 43.2.11
Armorer's Workshop Ver. 2.0.0-beta.31

**Comment by SAGESSE-CN** [comment]
fixed in next release

**Comment by SAGESSE-CN** [comment]
release in the beta.32
