### ISSUE TITLE
Keybind 1 Bug

### ISSUE THREAD

**Issue by lostopkk** [Armourers-Workshop/Armourers-Workshop#415]
when I downloaded the mod I thought my keyboard was bad because it had fallen, but it was actually the mod. watch the video and it exactly describes the bug.

https://github.com/Armourers-Workshop/Armourers-Workshop/assets/50776714/a378c950-c59c-4131-bdca-2369cdb36f3a

**Comment by SAGESSE-CN** [comment]
yes, I also noticed it in yesterday.

**Comment by SAGESSE-CN** [comment]
fixed in the beta.34
