### ISSUE TITLE
[CRASH] Trying to place the mannequin with Sodium on result in crash

### ISSUE THREAD

**Issue by Rimuchii** [Armourers-Workshop/Armourers-Workshop#416]
**To Reproduce**
Steps to reproduce the crash:
1. Launch a Minecraft world with both Armourer's Worshop and Sodium On
2. Hold out the Mannequin
3. Look anywhere to try to place the Mannequin
4. Crash

**Crash log**
https://pastebin.com/cEpZT5eh

**Additional context**
Crashed in every Shader, both mods used to work flawlessly without crash before.
Sodium is used with Sodium Extra.

**Comment by SAGESSE-CN** [comment]
pls update to laste version

**Comment by SAGESSE-CN** [comment]
This issue has been fixed in 1.19.2/1.19.4/1.20.1, but I do not recommend using 1.19.4. because 1.19.3 and 1.19.4 are no longer updated
