### ISSUE TITLE
[BUG] Item stack dupe with skinning table

### ISSUE THREAD

**Issue by GabrielB124** [Armourers-Workshop/Armourers-Workshop#417]
When an item stack is used in the skinning table, the remaining items remain in the first slot.

1. Have a stack of items and an item skin
2. Apply the skin to the stack of item
3. Duplication

Expected behavior
Either a single item is used and a single item results, or the entire stack is used and an entire stack results

Screenshots:
![2023-07-16_15 21 59](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/136336420/27d7b69a-cac2-43e0-a5fa-1a39957676b5)
![2023-07-16_15 22 12](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/136336420/bfe005f4-3060-4b29-ac8e-d9b42859ac95)

**Comment by SAGESSE-CN** [comment]
fixed in the v2.0.1, thx your report.
