### ISSUE TITLE
[Feature] Translation of the trident in the Korean translation

### ISSUE THREAD

**Issue by CreamWorldGit** [Armourers-Workshop/Armourers-Workshop#418]
**Describe the solution you'd like**
Add trident to Korean translation please translate (trident -> '삼지창')

**Additional context**
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/136564290/8625da4a-9209-4d48-aafe-24a37d49b6b8)

**Comment by SAGESSE-CN** [comment]
https://crowdin.com/project/armourers-workshop

**Comment by CreamWorldGit** [comment]
I checked it thank you!

**Comment by CreamWorldGit** [comment]
I checked it thank you!
