### ISSUE TITLE
Question about Uploading

### ISSUE THREAD

**Issue by xJohnx117** [Armourers-Workshop/Armourers-Workshop#419]
I wanted to know how to upload files, if it was in my face this whole time I would probably explode.

**Comment by SAGESSE-CN** [comment]
first you need have legal minecraft account, and then launcher it with your legal minecraft account.
in the singleplayer put the global skin library block, and open it. 
if you need to use GLS upload in the server, please make sure that your server has enabled online-mode
now your can joint GSL.

**Comment by xJohnx117** [comment]
But I did all that, so wheres the button to do it?

**Comment by SAGESSE-CN** [comment]
Github issue only for problem tracking, you can join discord for usage help.

**Comment by xJohnx117** [comment]
Yeah, I need a slap in the face for not knowing that.

**Comment by SAGESSE-CN** [comment]
https://discord.gg/5Z3KKvU
