### ISSUE TITLE
[BUG]Models can't be displayed from other people's viewpoints in multiplayer mode

### ISSUE THREAD

**Issue by fgr178707** [Armourers-Workshop/Armourers-Workshop#420]
I'm sure it's enabled on both the client and server side
Server-side game version 1.20
Client game version 1.20.1
Fabric frontend
I'm in someone else's view
![e783d1fc96e2f4a79d02530c2bc8e4ee](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/109357981/e46ce66a-b292-40e1-bd37-fb311548a079)

I'm in my own perspective
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/109357981/5c1b1b53-2643-416d-8e0a-78e957a66515)

**Comment by SAGESSE-CN** [comment]
try   https://discord.com/channels/277389736165769216/1132012002026459286/1134082464122404884

**Comment by SAGESSE-CN** [comment]
you need join aw discord sever first, and then got bate tester role

**Comment by fgr178707** [comment]
> 您需要先加入 aw Discord 服务器，然后获得 Bate 测试员角色

No, it's okay. The server rebooted.

**Comment by SAGESSE-CN** [comment]
This is a about probability problem, we suggest you update mod.
