### ISSUE TITLE
[BUG]Can I carry your Armourer's Workshop to Chinese Minecraft?

### ISSUE THREAD

**Issue by taose4874** [Armourers-Workshop/Armourers-Workshop#421]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug crash log**
Linking a debug crash log can help track down bugs. Holding down F3 + C for 10 seconds in game will force the a crash making a debug crash log. Please link your log using a site like https://pastebin.com/

**Additional context**

**Comment by SAGESSE-CN** [comment]
1: You are free to use it under the CC-BY-NCSA license, note you can't use any way to sell this mod. e.g. paid download.
2: You need careful some policy requirements of netease, e.g. the GSL does not necessarily meet the review requirements.
3: You will not get no technical support, e.g. 1.18.1 compatible.
