### ISSUE TITLE
[BUG] URL not working with discord, MC 1.12.2

### ISSUE THREAD

**Issue by eechrizzy** [Armourers-Workshop/Armourers-Workshop#422]
**Describe the bug**
I want to set a custom skin onto a mannequin, so I uploaded it to discord and copied the URL in hopes of it setting the skin in the image, exactly the same as it works with any other skin site.

**To Reproduce**
1. Spawn a mannequin
2. Click on the URL skin type
3. Upload a skin to discord as an image, and use that URL.
4. It doesnt work, and stays as a steve

**Expected behavior**
I expected it to load the skin that was in the link.
**Screenshots**
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/141836386/093f7e62-9b13-4d73-a5fa-b2ef16245ab1)

**Comment by SAGESSE-CN** [comment]
Sorry, 1.7/1.12 is no longer supported.

and the you can open it in the browser (private mode) first, the size of the picture must be 64x64 or 64x32
