### ISSUE TITLE
[Feature]Please make it for 1.19 version fabric only I'm dying for it!!

### ISSUE THREAD

**Issue by Gim-Jihwan** [Armourers-Workshop/Armourers-Workshop#423]
**

> Please make it for 1.19 version fabric only I'm dying for it!!

**

**Comment by SAGESSE-CN** [comment]
sorry? we provided version 1.19.2

**Comment by Gim-Jihwan** [comment]
Does Armour's Workshop 1.19.2 mode mean it also supports 1.19 version?

**Comment by SAGESSE-CN** [comment]
> > sorry? we provided version 1.19.2
> 
> Does Armour's Workshop 1.19.2 mode mean it also supports 1.19 version?

unverified, and the we can't support all versions. not many developers, not so much time for develop.
