### ISSUE TITLE
[BUG] Writes too many lines to log

### ISSUE THREAD

**Issue by SkpC9** [Armourers-Workshop/Armourers-Workshop#424]
**Describe the bug**
When using oculus, this mod writes too many lines to log file.

**To Reproduce**
1. install this mod 2.0.5, rubidium 0.6.5 and oculus 1.6.4. minecraft 1.20.1 forge 47.1.0.
2. download ComplementaryShaders_v4.7.2.
3. create a new world and enable shaders. (if shader is already enabled, disable then enable)
4. see the log full of 
`[21:28:38] [Render thread/INFO] [mo.pl.ar.ArmourersWorkshop/]: process iris shader: 
#version 330 core
// Generated by glsl-transformer
uniform mat4 iris_ProjMat;
in vec3 iris_Position;
uniform mat4 iris_ModelViewMatInverse;
uniform mat4 iris_ProjMatInverse; //and more lines`

**Expected behavior**
not this amount of lines

**Screenshots**

**Debug crash log**
https://pastebin.com/wAhBqhZ7

**Additional context**

**Comment by SAGESSE-CN** [comment]
not a bug, this is important log, because we will inject something in the shader pack. We only find shader's issue through the this log.

If you care about this very much, you can disable `debug shader` in client config
