### ISSUE TITLE
About linking tool [BUG]

### ISSUE THREAD

**Issue by lusher08** [Armourers-Workshop/Armourers-Workshop#429]
**Describe the bug**
When using linking tool to link between functioning block(chest, crafting table, etc..) with block skin, if the linked functioning block is far away from the user and when we right click the block skin to use the function - the functioning block's screen(for chest, the chest inventory screen) shows up for a very short time then disappears immediately.

**To Reproduce**
1. place the chest and block skin like 10 blocks away from each other.
2. link the chest with the block skin.
3. right click on the block skin to use the chest
4. the chest inventory shows up for like 0.5 second then disappears immediately.

**Expected behavior**
The chest inventory shows up then remains until we close it. 

**other experiment result**
When we place the chest and the block skin  close to each other, link them, and use block skin, the function works well. It only happens when they're far away from each other(I think this is related to the user's distance from the functioning block) Not only the chests, but also barrel, crafting table, furnace, and brewing stand causes same problem to the block skin when they're far away from the block skin.

**Comment by SAGESSE-CN** [comment]
this is correct(vanilla behavior), because for security reasons, these block will check the distance from the player.

**Comment by lusher08** [comment]
Ooh okay I get it :) Thank you for your quick response! 

Is there any plan for update to make it possible? For example, I think giving the block skin an address of the desired inventory slot(such as brewing stand's unique inventory slot address) might be the solution! If possible, user can create their own custom house full of custom furnitures(while keeping the linked fuctioning block away from the house, maybe by hiding them) :')

**Comment by SAGESSE-CN** [comment]
we can't implement it (security reasons), you need find or develop a mod to allows open menu from super far distance.
