### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Boulldog0** [Armourers-Workshop/Armourers-Workshop#430]
Hey, this isn't really a bug report but rather a question regarding a really known bug in 1.12.2 with Armorers Workshop. I wanted to know if there was a way to deactivate the dummies because they crash all the players in the surrounding area when they are placed on a server, and I would like to be able to resolve the problem for more than just that. I can't find anything on the internet. Can anyone answer me? Thanks !

( Sorry for the formatting, but i can find a catégories for questions )

**Comment by SAGESSE-CN** [comment]
sorry for the issue, but the 1.12 is no longer supported, so we can't release a new version to fix it.

1. you can try use some like tweeks mods to disable mannequin item.
2. you can try develop a mod disable mannequin register method by the mixin technology.
