### ISSUE TITLE
[BUG] recursive call to sendBlockUpdated

### ISSUE THREAD

**Issue by Sultia** [Armourers-Workshop/Armourers-Workshop#432]
**Describe the bug**
When adding more costume slots after max recursive call to sendBlockUpdated occurs.

**To Reproduce**
1. Use all mods in the list
2. Right click outfit slot add item
3. after maxing outfits slot right click again
4. See error in log

**Expected behavior**
In game message "You have max outfit slots"

**Screenshots**
N/A

**Debug crash log**
[latest.log](https://github.com/Armourers-Workshop/Armourers-Workshop/files/13418663/latest.log)

**Additional context**
N/A

**Comment by SAGESSE-CN** [comment]
sorry, but this is not an `aw` issue, it seems to be related to the door block. you need to check related mods.
