### ISSUE TITLE
[Feature] Permissions to use skins + Default Skins 

### ISSUE THREAD

**Issue by kiritodragneel** [Armourers-Workshop/Armourers-Workshop#433]
**Is your feature request related to a problem? Please describe.**
It is not, this is not an issue but an improvement that i feel would help servers myself included.

**Describe the solution you'd like**
As a server owner I would like to reward players for activity, achivements and other mile stones reached in game. 
I think if we could set a "Default" wearable to a player when they first join the server and then lock some wearbles behind 
permissions this would let us use some skins as rewards, For example on my server there are ranks for helping the community 
that are gained by just being active and useful, if we could give these people a wearble with their rank floating above their head 
to me this is cool. 

**Describe alternatives you've considered**
Honestly we did look at some plugins on spigot that put floating holograms above people but this is rather uggly, performant heavy and just not as cool of a concept, plus the player would not be able to add and remove it at their own descretion

**Comment by SAGESSE-CN** [comment]
https://github.com/Armourers-Workshop/Armourers-Workshop/wiki/KubeJS-Integrated

use kubejs you can setup default skin by each entity .
