### ISSUE TITLE
Workshop items require a server operator to wear them 

### ISSUE THREAD

**Issue by Linormi** [Armourers-Workshop/Armourers-Workshop#434]
**Describe the bug**
We have a server version 1.18.2 on Sponge Core, Forge version 40.2.14. And we use Armourers Workshop version 1.18.2 - 2.0.10
The problem is that when we use things from the library, the player needs to be a server operator to wear them. If there is no operator, the player cannot interact with the items and the library 

**Additional context**
I don't know how much of a bug this is, because last time on build 1.19.2 this didn't happen and anyone could contact the library and skins for weapon and so on. So I would like to know what could be the reason and how to fix it

**Comment by SAGESSE-CN** [comment]
not a bug https://github.com/Armourers-Workshop/Armourers-Workshop/wiki/Permission-System , some sever side changed default permission of the node.
