### ISSUE TITLE
[Feature] Support for Alex (slim arms) player model in Mannequin and Doll

### ISSUE THREAD

**Issue by PopSlime** [Armourers-Workshop/Armourers-Workshop#436]
## Description / 描述
In the current version, if an Alex skin (3-pixel-wide arms) is loaded into a Mannequin or a Doll, the texture is mapped incorrectly on the arms. Please consider auto-detecting the model type of the skin, or providing an option to toggle between the two player models.

当前版本下，如果在模特或玩偶上加载了一个 Alex 皮肤（三像素宽手臂），手臂的贴图不能正确地映射到模型上。请考虑自动检测皮肤的模型类型，或者提供一个切换这两个玩家模型的选项。

**Comment by RadiantUwU** [comment]
Waiting on this ^

**Comment by zehuman** [comment]
this would save me so much work ;-;

**Comment by SAGESSE-CN** [comment]
Fixed in the 3.0.0-beta.3
