### ISSUE TITLE
How do I get player data?

### ISSUE THREAD

**Issue by RacoBoss** [Armourers-Workshop/Armourers-Workshop#438]
1. I need to load or save the player's Armorer Workshop data to link the BungeeCord, How do I do this?
2. Armorer Workshop also released a plugin. How do I get player data in version 1.19?

**Comment by SAGESSE-CN** [comment]
1. are you using multiple servers?
2. I don't understand what you want.

**Comment by RacoBoss** [comment]
Yes, the basic player data has been linked using mysql, but I am leaving a question because I need to link Armorer Workshop data.

**Comment by SAGESSE-CN** [comment]
We use persistence data API provided by bukkit. If you need to support mysql, you need to use a plug-in yourself to solve this problem.

**Comment by RacoBoss** [comment]
Are you saying that I need to create a plugin using the system provided at https://github.com/SAGESSE-CN/Armourers-Workshop-Plugin?

**Comment by SAGESSE-CN** [comment]
You can try HuskSync, It will synchronize persistence data  for you.

**Comment by RacoBoss** [comment]
No.. Server data linking has already been completed, but only Armorer Workshop data remains, so I asked what to do.

**Comment by SAGESSE-CN** [comment]
when you install it, it will solve the data problem of aw

**Comment by SAGESSE-CN** [comment]
When the aw data is synchronized to another server, the skin will be displayed when the player joins the server. Of course, you need to manually synchronize the files in the skin database.
