### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YuHazine** [Armourers-Workshop/Armourers-Workshop#441]
**Describe the bug**

If you look at the Armorer Workshop after applying the Excalibur Resource Pack, most of the items turn black when in the inventory, making it difficult to distinguish them. Fortunately, there is no problem when holding it in the hand or installing it, but there is a big problem that it is difficult to distinguish it in the inventory.
 
Also, a bigger problem is that after applying the Excalibur resource pack, an error occurs in which certain items and blocks of other modes turn black, making it difficult to distinguish them.
 
Could you please contact the creator of the resource pack to solve the problem?
 
Thank you for reading this long post and I hope only happy things happen to you always!
 
- in korea

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/2c3a3bd6-f9b0-40fb-8892-963201ec0fd3">
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/24159bd8-660d-4d67-bcc7-478597042022">

it look is normal.
