### ISSUE TITLE
[Feature]Request for Compatibility Improvement between First-person Model and Armourer's Workshop Mods

### ISSUE THREAD

**Issue by WeisanEarl** [Armourers-Workshop/Armourers-Workshop#442]
I have been using the First-person Model mod, which provides a first-person perspective with a detailed character model. While both mods work independently without causing any game crashes, there is a compatibility issue between them.

Specifically, when using the Armourer's Workshop mod to view or interact with armor models, the head model from the First-person Model mod occasionally obstructs the player's view.

https://www.curseforge.com/minecraft/mc-mods/first-person-model
https://www.curseforge.com/minecraft/mc-mods/first-person-model
![huge_2024-02-05_16 03 20](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/103826631/3d3ecc6a-5a13-4593-bb89-c8bdb87e0f4d)

Thank you for your time and consideration. I look forward to any updates you may have in the future and am eager to see how you continue to improve the Armourer's Workshop mod.
Thanks a lot👍

**Comment by SAGESSE-CN** [comment]
What are the specific parts that are occasionally obstructs?

Currently possible bigger wings or bigger body parts. becauses fpm to special processing of the head. 

If you can provide the armour file, it will be easier to determine the problem

**Comment by papamaionise** [comment]
Alternatively you can go into first person model mod's settings and shift the camera a little away from player model.

**Comment by SAGESSE-CN** [comment]
update `First-person Model ` to  latest version to resolve this issue
