### ISSUE TITLE
[Feature] Add support for the Velocity proxy server."

### ISSUE THREAD

**Issue by windy664** [Armourers-Workshop/Armourers-Workshop#443]
**Is your feature request related to a problem? Please describe.**
"When using the Velocity proxy server, unable to access the backend, with the prompt: 'Please install the correct Armourers Workshop to play on this server!'"
用Velocity跨服时，提示'Please install the correct Armourers Workshop to play on this server!'
**Describe the solution you'd like**

Delete the relevant code here or devlop a plugin for Velocity proxy
删除这相关代码，或者开发一个Velocity插件

https://github.com/Armourers-Workshop/Armourers-Workshop/blob/develop/fabric/src/main/java/moe/plushie/armourers_workshop/init/platform/fabric/NetworkManagerImpl.java
`        public void onServerHandshake(MinecraftServer server, ServerLoginPacketListenerImpl handler, boolean understood, FriendlyByteBuf buf, ServerLoginNetworking.LoginSynchronizer synchronizer, PacketSender responseSender) {
            if (!ModConfig.Common.enableProtocolCheck) {
                return;
            }
            if (understood) {
                String version = buf.readUtf(Short.MAX_VALUE);
                if (version.equals(channelVersion)) {
                    return;
                }
            }
            handler.disconnect(Component.literal("Please install correct Armourers Workshop to play on this server!"));
        }`

**Describe alternatives you've considered**

**Additional context**

**Comment by SAGESSE-CN** [comment]
pls set enableProtocolCheck to false if you needs
