### ISSUE TITLE
[BUG]DUPE GLITCH BUG ""IMPORTANT!! FIX""

### ISSUE THREAD

**Issue by Meidde** [Armourers-Workshop/Armourers-Workshop#444]
**Describe the bug**
There is a bug to duplicate Skins, it started from version 1.20.1-2.0.7
when the skins became stacks of 64 items, to double it just put 2 skins in your hand and right click to equip, and it will be equipped 2 but one will remain in your hand

It is very important to fix this problem considering that large servers are used and may have problems

![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/141171526/0e79cede-dff7-4303-a0b0-329ef4138340)

**To Reproduce**
1. Put 2 Skins in hotbar/HAND
2. Rightclick to equip 
3. Open your WARDROBE and see 2 skins equipped and 1 in your hand
4. Has infinite skins with this GLITCH

Versions Tested: 1.20.1-2.0.7 > 1.20.1 - 2.0.11

**Comment by SAGESSE-CN** [comment]
fixed in next release
