### ISSUE TITLE
[BUG] painting only shades blocks in editing

### ISSUE THREAD

**Issue by MushroomDSM** [Armourers-Workshop/Armourers-Workshop#445]
whenever i use a paintbrush or a roller, blocks are only shaded, but are fully colored when turned into an item, making it stupidly hard to color things properly, ive tried switching the paint type but nada, its always just shaded, ive tried turning off shaders and that didnt help either, is this a mod conflict? am i doing something wrong? do i have a setting on/off? or just a random bug? using fabric-1.19.2-2.1.0

update: appears to be a mod conflict, opened the game with only armourers workshop and it seems to be working fine now

**Comment by GalacticRy** [comment]
From my experience, The shading on the blocks is due to Iris/Sodium for fabric, specifically the biome blend feature, setting it to 0 fixed the issue for me.

**Comment by SAGESSE-CN** [comment]
Known issues for sodium biome blend
