### ISSUE TITLE
game crashes when sleeping in custom bed blocks

### ISSUE THREAD

**Issue by papamaionise** [Armourers-Workshop/Armourers-Workshop#448]
as the title says
I'm using realistic sleep mod alongside

**Comment by papamaionise** [comment]
ok game crashes even with out the realistic sleep mod

**Comment by papamaionise** [comment]
sometimes its a freeze

**Comment by SAGESSE-CN** [comment]
game and mod version?

**Comment by papamaionise** [comment]
2.1.0 mod version
1.20.1 minecraft version

**Comment by SAGESSE-CN** [comment]
fixed in the 2.1.2
