### ISSUE TITLE
compatibility with 3d skin layer

### ISSUE THREAD

**Issue by papamaionise** [Armourers-Workshop/Armourers-Workshop#449]
![2024-03-01_16 55 40](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/126779287/73b4e78e-8e87-408f-929c-153f321db0df)
![2024-03-01_16 56 03](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/126779287/0c52e71d-4a41-4294-8df9-0e178bd6a7f7)

the 3d skin layer doesn't disappear when a player outfit is applied the vanilla skin is still there clipping through the outfit

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/165dd423-12d1-4e38-8e25-617809e9c549">
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/e7f4c16f-9a55-4a21-b3bc-bad52b1077ab">

everything is fine, no compatibility issues found
