### ISSUE TITLE
Custom items preview Tool tip background texture breaks with menu resource pack

### ISSUE THREAD

**Issue by papamaionise** [Armourers-Workshop/Armourers-Workshop#450]
![2024-03-01_17 00 28](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/126779287/e5c75b77-261a-44b9-a6a2-c91d33074de6)

**Comment by SAGESSE-CN** [comment]
I can’t reproduce this problem. Can you try aw mod only + resource pack?

**Comment by SAGESSE-CN** [comment]
Please provide more information and reopen

**Comment by papamaionise** [comment]
> Please provide more information and reopen

sorry for late reply I only use this git account for mod reports

here's the modpack I'm using
https://mega.nz/file/13AiFBqI#Ksp7Z2ugsQYgcmPMU0gNpBMwyyr_tm526iffLoPxIJU
