### ISSUE TITLE
default mannequin z fighting and clipping through outfit

### ISSUE THREAD

**Issue by papamaionise** [Armourers-Workshop/Armourers-Workshop#451]
![2024-03-01_18 04 14](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/126779287/3734e1da-f94d-4e2a-a3b2-ca01bb3bff70)

It be nice if mannequins disappear or maybe they are just small like the armor stand

**Comment by SAGESSE-CN** [comment]
you need enable model override in the armourer when create skin
