### ISSUE TITLE
[Feature] 1.20.4 Support

### ISSUE THREAD

**Issue by mmsheeks** [Armourers-Workshop/Armourers-Workshop#453]
**Is your feature request related to a problem? Please describe.**
I'm about to launch an SMP, we'd love to run this, but are also running latest version for the preview features. Any chance at an update?

**Describe the solution you'd like**
Patch for 1.20.4 compatibility

**Describe alternatives you've considered**
We can use datapacks and resource packs as a workaround, but this mod is much more intuitive for players.

**Additional context**
Happy to fork and do some of the work if you can point me in the right direction.

**Comment by SAGESSE-CN** [comment]
The next supported version will be 1.21, because 1.20.4 is a temp version.

we basically done the 1.20.4 port, but it won't be released. 

you can build jar by self
https://github.com/SAGESSE-CN/Armourers-Workshop/tree/adv
