### ISSUE TITLE
Unable to use Skin url 1.8.9

### ISSUE THREAD

**Issue by Alexandaar01** [Armourers-Workshop/Armourers-Workshop#454]
I can't for the life of me use this thing. When I load an image into Imgur, its always zoomed out, and when I click edit, it's always blurry, I have tried with 64x64 skins and 128x128 skins and nothing works I have tried resizing, reformatting, and trying new skin makers and editors, but nothing works, When I do it, I only get 2 types of responses, I have tried other people's links too, even ones from YouTube videos, and nothing works. Please give me some kind of solution. I have attached some screenshots of the only 2 things I see when I try to use the url.

![2024-03-19_12 41 46](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/93018972/b2541f1d-c679-44e4-a956-64bd2c31cc75)
![2024-03-19_12 42 48](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/93018972/ae0ee084-656d-47e2-804c-02e17aee34a2)

**Comment by SAGESSE-CN** [comment]
imgur  changed their picture view strategy, in other words, although the url is still the end of png, but it is a webpage.
