### ISSUE TITLE
Brush To change ONLY paint type [Feature]

### ISSUE THREAD

**Issue by Granite-Gaming** [Armourers-Workshop/Armourers-Workshop#455]
**Is your feature request related to a problem? Please describe.**
So I accidently used "none" as the paint type for a portion of a model. This caused parts of it to appear invisible and I had already used the blend took to smooth colors making it harder to revert. 

**Describe the solution you'd like**
Potentially a brush that changes exclusively the paint type leaving color alone. Potentially a "Gloss" spray can?

**Describe alternatives you've considered**
either redoing the portion that was broke (can't re blend due to other blocks around.)
using color picker, brush, and color mixer to repaint each block

**Comment by SummerOfShadows** [comment]
Use the hue tool, turn off everything but paint type and it will change it to that paint type and not effect the color.
![image (17)](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/113380506/5297bb9e-614b-4837-9147-530485964471)

**Comment by SAGESSE-CN** [comment]
Added next release
