### ISSUE TITLE
Creative Tools? [Feature]

### ISSUE THREAD

**Issue by Granite-Gaming** [Armourers-Workshop/Armourers-Workshop#457]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I am annoyed having to go back and fourth between a color mixer and the tools in creative mode. Having a tool that has a color mixer menu integrated would be convenient for creative mode users.

**Describe the solution you'd like**
Creative mode tools with color/paint tabs. Potentially 1 tool with selectable tool types and (3) tabs? 
Tab examples
- Tool Selector (eyedropper included?)
- Tool Settings 
- Color Changer

**Describe alternatives you've considered**
continue to constantly grab new tools from the creative menue and traveling back and fourth between build and color mixer

**Comment by SAGESSE-CN** [comment]
hold the paint tool and shift + right click to open color plane
