### ISSUE TITLE
Apotheosis Stats Expire[BUG]

### ISSUE THREAD

**Issue by trynity121** [Armourers-Workshop/Armourers-Workshop#460]
I was making custom weapons for the server where I play with my friends and I noticed that if you put the weapons in the inventory (not in the item bar), these weapons modified with commands from the "Apotheosis" mod ( +50% draw speed etc.) they reset and removes all the stats made, is there a way to solve it?

the bug basically removes the stats from the item when it is placed in the inventory

![2024-04-16_04 21 16](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/50847078/d6e45f92-026e-425b-90ca-d3a295cd2f3f)

![2024-04-16_04 21 40](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/50847078/5832a2ae-96b1-45fe-8804-9c375e662b61)

as you can see the "+50% Max Mana" stat goes down as soon as it is placed in the inventory

**Comment by trynity121** [comment]
i know is this mod " Armourer's Workshop" because other no custom weapons don't do this.

**Comment by SAGESSE-CN** [comment]
We will not modify the properties of any items

**Comment by SAGESSE-CN** [comment]
close, because it's not we issues.
