### ISSUE TITLE
[BUG] Head not rendering

### ISSUE THREAD

**Issue by ALEILGOD** [Armourers-Workshop/Armourers-Workshop#463]
When i use the armorer the head of my player is showing for the first ten blocks but when i go up it doesn't render anymore

1. Place the armorer
2. go up to the middle of the head
3. Head not rendering at a certain point

**Expected behavior**
Head renders ( but it doesn't)

**Debug crash log**
https://pastebin.com/JVDrLrJi

**Additional context**
I'm using other mods like embeddium and some extras

**Comment by ALEILGOD** [comment]
https://github.com/Armourers-Workshop/Armourers-Workshop/assets/116183327/9514b213-c693-4e25-8d84-96f541c19652

**Comment by SAGESSE-CN** [comment]
fixed in next 3.0 release

**Comment by SAGESSE-CN** [comment]
fixed in next 3.0 release
