### ISSUE TITLE
[1.20.1] AW Bug With Oculus 1.7.0

### ISSUE THREAD

**Issue by CiciHoneyBee** [Armourers-Workshop/Armourers-Workshop#464]
**Describe the bug**
Hey! I had updated Oculus to 1.7.0 in my modpack and noticed a bug with the Armourer's Workshop mod while shaders were enabled. When wearing an AW skin while in third person, the skin expanded and blocked the entire screen. I was using both unbound and reimagined complementary shaders. I had reported this to Oculus first but they told me to take the issue here.

**To Reproduce**
1. Download AW (I've tested both on AW 2.1.2 release and 3.0.0 beta)
2. Download Oculus 1.7.0
3. Download Embeddium 0.3.17
4. Start the game and equip any skin
5. Enable shaders 
6. Go into third person

**Expected behavior**
Expected screen to not be blocked by AW skin.

**Screenshots**
Player wearing AW skin in Oculus 1.6.15a:
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/166247139/35101357-0c4e-4f72-94d8-f8cae564439e)

Player wearing AW skin in Oculus 1.7.0:
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/166247139/46d342dd-0b76-4469-a592-e23e8e6a544c)

**Debug crash log**
Linking a debug crash log can help track down bugs. Holding down F3 + C for 10 seconds in game will force the a crash making a debug crash log. Please link your log using a site like https://pastebin.com/

**Additional context**

**Comment by SAGESSE-CN** [comment]
fixed in the 2.1.3
